site_name: xg f2e-doc
version: 1.0.0
pages:
- [index.md, index]
- [seed.md, seed]
- [lang.md, lang]
- [uri.md, uri]
- [event.md, event]
- [support.md, support]
- [loader.md, loader]
- [cookie.md, cookie]
- [date.md, date]
- [request.md, request]
